spring:
  application:
    name: flowmat
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/flowmat}
    username: ${DB_USERNAME:flowmat}
    password: ${DB_PASSWORD:flowmat}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

server:
  servlet:
    context-path: /api

logging:
  level:
    org.hibernate.SQL: debug
